
name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate and Upload Test Report
      if: always()
      run: |
        mkdir -p maven
        cp target/surefire-reports/*.xml maven/test-results.xml
          
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.3.5
      with:
        # Artifact name
        name: tet-results
        path: maven/test-results.xml
  
  
          
