name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Main Repository

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Main Project
      run: mvn -B package --file pom.xml

    - name: Clone Test Repository
      env:
        REPO_URL: https://github.com/eshonkulov-asliddin/autotest-java-lab-test.git
      run: |
        git clone --depth 1 $REPO_URL temp-test-repo
        mkdir -p test
        cp -r temp-test-repo/src/test/* src/test/
        rm -rf temp-test-repo

    - name: Build Test Project
      run: mvn -B test --file pom.xml

    - name: Generate and Upload Test Results
      run: |
        mkdir -p junit
        mvn surefire-report:report -DoutputDirectory=junit
        mv junit/TEST-*.xml junit/test-results.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: junit/test-results.xml

    - name: Clean up
      run: rm -rf test
