name: Build and Test Maven Project

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        id: build
        run: |
          mvn -B clean package --file pom.xml

      - name: Run Tests
        id: test
        run: |
          mvn -B test --file pom.xml

      - name: Generate and Upload Test Report
        if: always()  # Run this step regardless of previous step result
        run: |
          mkdir -p junit
          cp target/surefire-reports/*.xml junit/test-results.xml

      - name: Upload Test Report
        if: always()  # Upload test report even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: junit/test-results.xml

      - name: Get Artifact Download URL
        if: always()
        id: artifact-download-url
        run: |
          echo "::set-output name=url::https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"

      - name: Notify Webhook
        if: always()  # Run this step regardless of previous step result
        run: |
          if [ "${{ steps.build.outcome }}" == "success" ]; then
            STATUS="SUCCESS"
          else
            STATUS="FAILURE"
          fi
          REPO_NAME="${{ github.repository }}"
          REPO_OWNER="${{ github.repository_owner }}"
          BRANCH_NAME="${{ github.ref }}"
          COMMIT_SHA="${{ github.sha }}"
          RUN_ID="${{ github.run_id }}"
          RUN_NUMBER="${{ github.run_number }}"
          ARTIFACT_URL="${{ steps.artifact-download-url.outputs.url }}"
          USERNAME="${{ github.actor }}"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "status": "'"$STATUS"'",
                  "repository": {
                    "name": "'"$REPO_NAME"'",
                    "owner": "'"$REPO_OWNER"'"
                  },
                  "branch": "'"$BRANCH_NAME"'",
                  "commit": "'"$COMMIT_SHA"'",
                  "run_id": "'"$RUN_ID"'",
                  "run_number": "'"$RUN_NUMBER"'",
                  "artifact_url": "'"$ARTIFACT_URL"'",
                  "username": "'"$USERNAME"'"
                }' \
            https://eshonkulov-asliddin.jprq.app/workflow/results
