name: Build and Test Maven Project

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        id: build
        run: |
          mvn -B clean package --file pom.xml || true  # Run build, but don't fail the step if it fails

      - name: Run Tests
        id: test
        run: |
          mvn -B test --file pom.xml || true  # Run tests, but don't fail the step if it fails

      - name: Generate and Upload Test Report
        if: always()  # Run this step regardless of previous step result
        run: |
          mkdir -p junit
          cp target/surefire-reports/*.xml junit/test-results.xml

      - name: Upload Test Report
        if: always()  # Upload test report even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: junit/test-results.xml

      - name: Upload Build Artifact
        if: success()  # Only upload if build is successful
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar
