name: Build and Test Maven Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      run-id: ${{ steps.build.outputs.run-id }}
      run-number: ${{ steps.build.outputs.run-number }}
      artifact-download-url: ${{ steps.artifact-download-url.outputs.url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        id: build
        run: |
          mvn -B clean package --file pom.xml
          echo "::set-output name=run-id::${{ github.run_id }}"
          echo "::set-output name=run-number::${{ github.run_number }}"

      - name: Run Tests
        id: test
        run: mvn -B test --file pom.xml

      - name: Generate and Upload Test Report
        if: always()
        run: |
          mkdir -p junit
          cp target/surefire-reports/*.xml junit/test-results.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: junit/test-results.xml

      - name: Get Artifact Download URL
        if: always()
        id: artifact-download-url
        run: echo "::set-output name=url::https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Notify Webhook
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            STATUS="SUCCESS"
          else
            STATUS="FAILURE"
          fi
          REPO_NAME="${{ github.repository }}"
          REPO_OWNER="${{ github.repository_owner }}"
          BRANCH_NAME="${{ github.ref }}"
          COMMIT_SHA="${{ github.sha }}"
          RUN_ID="${{ needs.build.outputs.run-id }}"
          RUN_NUMBER="${{ needs.build.outputs.run-number }}"
          ARTIFACT_URL="${{ needs.build.outputs.artifact-download-url }}"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
                  "status": "'"$STATUS"'",
                  "repository": {
                    "name": "'"$REPO_NAME"'",
                    "owner": "'"$REPO_OWNER"'"
                  },
                  "branch": "'"$BRANCH_NAME"'",
                  "commit": "'"$COMMIT_SHA"'",
                  "runId": "'"$RUN_ID"'",
                  "runNumber": "'"$RUN_NUMBER"'",
                  "artifactUrl": "'"$ARTIFACT_URL"'"
                }' \
            https://eshonkulov-asliddin.jprq.app/workflow/results
