name: Build and Test Maven Project

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        id: build
        run: mvn -B package --file pom.xml 2>&1 | tee build_output.log
        continue-on-error: true
      
      - name: Create directory for test results
        run: mkdir -p junit
        
      - name: Generate Build Error Report
        if: steps.build.outcome == 'failure'
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > junit/test-results.xml
          echo '  <testsuite name="Build Errors" tests="1" failures="1">' >> junit/test-results.xml
          echo '    <testcase classname="Build" name="Build Script">' >> junit/test-results.xml
          echo '      <failure type="error" message="Build failed. See log for details."><![CDATA[' >> junit/test-results.xml
          cat build_output.log >> junit/test-results.xml
          echo '      ]]></failure>' >> junit/test-results.xml
          echo '    </testcase>' >> junit/test-results.xml
          echo '  </testsuite>' >> junit/test-results.xml

      - name: Run Tests and Generate Report
        if: steps.build.outcome == 'success'
        run: mvn surefire:test

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/*.xml
